#!/bin/bash

# Screenshot Helper Script for Tic Tac Toe Mission Control
# This script helps you capture and optimize screenshots for the README

echo "📸 Screenshot Helper for Tic Tac Toe Mission Control"
echo "=================================================="
echo ""

# Create screenshots directory
mkdir -p screenshots
cd screenshots

echo "✅ Created screenshots/ directory"
echo ""
echo "📋 Screenshots needed:"
echo ""
echo "1. auth-screen.png"
echo "   - Open: http://localhost:3000"
echo "   - Show: Login screen with 3D space background"
echo "   - Size: 1200x800px"
echo ""
echo "2. game-board.png"
echo "   - Start a game (vs AI or multiplayer)"
echo "   - Show: Game board with some moves"
echo "   - Size: 1200x800px"
echo ""
echo "3. victory-share.png"
echo "   - Win a game"
echo "   - Show: Victory modal with share buttons"
echo "   - Size: 1200x800px"
echo ""
echo "4. space-gallery.png"
echo "   - Click 🌌 SPACE button"
echo "   - Show: Solar system or stars view"
echo "   - Size: 1200x800px"
echo ""
echo "5. mobile-view.png"
echo "   - Open browser dev tools (F12)"
echo "   - Toggle device toolbar (Ctrl+Shift+M)"
echo "   - Select iPhone or Android"
echo "   - Show: Mobile login or game screen"
echo "   - Size: 400x800px"
echo ""
echo "🎥 For demo video:"
echo "   - Use OBS Studio: https://obsproject.com/"
echo "   - Or use built-in screen recorder"
echo "   - Record 2-3 minutes showing all features"
echo ""
echo "📦 After taking screenshots:"
echo "   1. Save them in this screenshots/ folder"
echo "   2. Run: ./optimize-screenshots.sh (if available)"
echo "   3. Or manually optimize with ImageMagick"
echo "   4. Commit: git add screenshots/ && git commit -m 'Add screenshots'"
echo "   5. Push: git push"
echo ""
echo "🌐 Upload video:"
echo "   Option 1: GitHub"
echo "     - Go to any issue"
echo "     - Drag & drop video"
echo "     - Copy URL and add to README"
echo ""
echo "   Option 2: YouTube"
echo "     - Upload to YouTube"
echo "     - Copy video ID"
echo "     - Add to README"
echo ""
echo "✨ Tips:"
echo "   - Use high resolution (1920x1080 for recording)"
echo "   - Show all major features"
echo "   - Keep video under 5 minutes"
echo "   - Add background music (optional)"
echo "   - Use smooth transitions"
echo ""
echo "📸 Screenshot tools:"
echo "   - Windows: Snipping Tool, Win+Shift+S"
echo "   - Mac: Cmd+Shift+4"
echo "   - Linux: Spectacle, Flameshot, gnome-screenshot"
echo "   - Browser: F12 → Device toolbar → Screenshot"
echo ""
echo "🎬 Video recording tools:"
echo "   - OBS Studio (Free, all platforms)"
echo "   - ShareX (Windows)"
echo "   - QuickTime (Mac)"
echo "   - SimpleScreenRecorder (Linux)"
echo "   - Browser extensions: Loom, Screencastify"
echo ""
echo "Ready to capture! 🚀"
