#!/bin/bash

# Screenshot Guide Generator
# This script helps you capture all necessary screenshots

echo "📸 Screenshot Capture Guide"
echo "============================"
echo ""
echo "Visit your live site: https://tictactoe-multiplayer-kx9u.onrender.com/"
echo ""
echo "Required Screenshots:"
echo ""
echo "1. 🎨 Banner (1200x400px)"
echo "   - Full screen of the auth page"
echo "   - Save as: screenshots/banner.png"
echo ""
echo "2. 🔐 Login Screen"
echo "   - Auth page with login tab active"
echo "   - Save as: screenshots/login.png"
echo ""
echo "3. 🏠 Lobby"
echo "   - Main lobby with user stats visible"
echo "   - Save as: screenshots/lobby.png"
echo ""
echo "4. 🎮 Game Board"
echo "   - Active game in progress"
echo "   - Save as: screenshots/game.png"
echo ""
echo "5. 🏆 Victory Screen"
echo "   - Game over overlay with fireworks"
echo "   - Save as: screenshots/victory.png"
echo ""
echo "6. 🌌 Space Gallery - Solar System"
echo "   - Space gallery with solar system tab active"
echo "   - Save as: screenshots/space-solar.png"
echo ""
echo "7. ⭐ Space Gallery - Stars"
echo "   - Space gallery with stars tab active"
echo "   - Save as: screenshots/space-stars.png"
echo ""
echo "8. 🌫️  Space Gallery - Nebulae"
echo "   - Space gallery with nebulae tab active"
echo "   - Save as: screenshots/space-nebulae.png"
echo ""
echo "9. 📱 Mobile Game"
echo "   - Game view on mobile (use browser dev tools)"
echo "   - Save as: screenshots/mobile-game.png"
echo ""
echo "10. 📱 Mobile Lobby"
echo "    - Lobby view on mobile"
echo "    - Save as: screenshots/mobile-lobby.png"
echo ""
echo "11. 🎬 Video Thumbnail (1280x720px)"
echo "    - Attractive thumbnail for video"
echo "    - Save as: screenshots/video-thumbnail.png"
echo ""
echo "═══════════════════════════════════════════════════════"
echo ""
echo "📹 Demo Video Recording Guide"
echo "============================"
echo ""
echo "Record a 2-3 minute video showing:"
echo ""
echo "1. Registration (0:00-0:20)"
echo "   - Show registration form"
echo "   - Create account"
echo "   - Show lobby"
echo ""
echo "2. Create Room (0:20-0:40)"
echo "   - Click 'Create Room'"
echo "   - Show room code"
echo "   - Copy code"
echo ""
echo "3. Join Room (0:40-1:00)"
echo "   - Open incognito window"
echo "   - Register second user"
echo "   - Join with code"
echo ""
echo "4. Gameplay (1:00-1:40)"
echo "   - Play a full game"
echo "   - Show chat"
echo "   - Show victory animation"
echo "   - Click rematch"
echo ""
echo "5. AI Mode (1:40-2:00)"
echo "   - Leave room"
echo "   - Play vs AI"
echo "   - Show AI moves"
echo ""
echo "6. Space Gallery (2:00-2:30)"
echo "   - Click 🌌 button"
echo "   - Switch tabs"
echo "   - Click objects"
echo "   - Show info panels"
echo "   - Zoom and pan"
echo ""
echo "7. Mobile View (2:30-3:00)"
echo "   - Open dev tools"
echo "   - Toggle device toolbar"
echo "   - Show responsive design"
echo "   - Test touch interactions"
echo ""
echo "Save as: screenshots/demo-video.mp4"
echo ""
echo "═══════════════════════════════════════════════════════"
echo ""
echo "🛠️  Tools for Screenshots:"
echo ""
echo "Browser Built-in:"
echo "  • Chrome: F12 → Device Toolbar → Screenshot icon"
echo "  • Firefox: Right-click → Take Screenshot"
echo "  • Safari: Develop → Show Web Inspector → Screenshot"
echo ""
echo "Third-party (Free):"
echo "  • Lightshot: https://prnt.sc/"
echo "  • ShareX (Windows): https://getsharex.com/"
echo "  • Flameshot (Linux): https://flameshot.org/"
echo "  • Skitch (Mac): https://evernote.com/products/skitch"
echo ""
echo "🎥 Tools for Video Recording:"
echo ""
echo "  • OBS Studio (All platforms): https://obsproject.com/"
echo "  • Loom (Browser): https://www.loom.com/"
echo "  • QuickTime (Mac): Built-in"
echo "  • Xbox Game Bar (Windows): Win+G"
echo ""
echo "═══════════════════════════════════════════════════════"
echo ""
echo "📁 After capturing, organize like this:"
echo ""
echo "screenshots/"
echo "├── banner.png"
echo "├── login.png"
echo "├── lobby.png"
echo "├── game.png"
echo "├── victory.png"
echo "├── space-solar.png"
echo "├── space-stars.png"
echo "├── space-nebulae.png"
echo "├── mobile-game.png"
echo "├── mobile-lobby.png"
echo "├── video-thumbnail.png"
echo "└── demo-video.mp4"
echo ""
echo "Then run:"
echo "  git add screenshots/"
echo "  git commit -m 'Add screenshots and demo video'"
echo "  git push"
echo ""
echo "✅ Done! Your README will display all media automatically."
echo ""
